// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about from "./routes/about.tsx";
import * as $accreditation from "./routes/accreditation.tsx";
import * as $akvaplanist from "./routes/akvaplanist.tsx";
import * as $api_mynewsdesk_index from "./routes/api/mynewsdesk/index.ts";
import * as $api_mynewsdesk_type_path_ from "./routes/api/mynewsdesk/type/[...path].ts";
import * as $api_mynewsdesk_year_path_ from "./routes/api/mynewsdesk/year/[...path].ts";
import * as $api_projects from "./routes/api/projects.ts";
import * as $api_slug_type_ from "./routes/api/slug/[type].ts";
import * as $article_slug_ from "./routes/article/[slug].tsx";
import * as $careers from "./routes/careers.tsx";
import * as $dcat from "./routes/dcat.tsx";
import * as $document_slug_ from "./routes/document/[slug].tsx";
import * as $documents from "./routes/documents.tsx";
import * as $doi from "./routes/doi.tsx";
import * as $fakturering from "./routes/fakturering.tsx";
import * as $home from "./routes/home.tsx";
import * as $images from "./routes/images.tsx";
import * as $index from "./routes/index.tsx";
import * as $legacy from "./routes/legacy.tsx";
import * as $legacy_pages_redirect from "./routes/legacy_pages_redirect.tsx";
import * as $media_slug_ from "./routes/media/[slug].tsx";
import * as $ms_louise from "./routes/ms-louise.tsx";
import * as $mynewsdesk_slug_ from "./routes/mynewsdesk/[slug].tsx";
import * as $nav from "./routes/nav.tsx";
import * as $news from "./routes/news.tsx";
import * as $null from "./routes/null.tsx";
import * as $policies from "./routes/policies.tsx";
import * as $pref from "./routes/pref.tsx";
import * as $project from "./routes/project.tsx";
import * as $projects from "./routes/projects.tsx";
import * as $pubs from "./routes/pubs.tsx";
import * as $research from "./routes/research.tsx";
import * as $research_topics from "./routes/research_topics.tsx";
import * as $search from "./routes/search.tsx";
import * as $service_topics from "./routes/service_topics.tsx";
import * as $services from "./routes/services.tsx";
import * as $sitemap_txt from "./routes/sitemap.txt.ts";
import * as $topics from "./routes/topics.tsx";
import * as $usr from "./routes/usr.tsx";
import * as $videos from "./routes/videos.tsx";
import * as $HScrollWithDynamicImage from "./islands/HScrollWithDynamicImage.tsx";
import * as $button_open_dialog from "./islands/button_open_dialog.tsx";
import * as $doi_search from "./islands/doi_search.tsx";
import * as $lang_switcher from "./islands/lang_switcher.tsx";
import * as $text from "./islands/text.tsx";
import * as $theme_switcher from "./islands/theme_switcher.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about.tsx": $about,
    "./routes/accreditation.tsx": $accreditation,
    "./routes/akvaplanist.tsx": $akvaplanist,
    "./routes/api/mynewsdesk/index.ts": $api_mynewsdesk_index,
    "./routes/api/mynewsdesk/type/[...path].ts": $api_mynewsdesk_type_path_,
    "./routes/api/mynewsdesk/year/[...path].ts": $api_mynewsdesk_year_path_,
    "./routes/api/projects.ts": $api_projects,
    "./routes/api/slug/[type].ts": $api_slug_type_,
    "./routes/article/[slug].tsx": $article_slug_,
    "./routes/careers.tsx": $careers,
    "./routes/dcat.tsx": $dcat,
    "./routes/document/[slug].tsx": $document_slug_,
    "./routes/documents.tsx": $documents,
    "./routes/doi.tsx": $doi,
    "./routes/fakturering.tsx": $fakturering,
    "./routes/home.tsx": $home,
    "./routes/images.tsx": $images,
    "./routes/index.tsx": $index,
    "./routes/legacy.tsx": $legacy,
    "./routes/legacy_pages_redirect.tsx": $legacy_pages_redirect,
    "./routes/media/[slug].tsx": $media_slug_,
    "./routes/ms-louise.tsx": $ms_louise,
    "./routes/mynewsdesk/[slug].tsx": $mynewsdesk_slug_,
    "./routes/nav.tsx": $nav,
    "./routes/news.tsx": $news,
    "./routes/null.tsx": $null,
    "./routes/policies.tsx": $policies,
    "./routes/pref.tsx": $pref,
    "./routes/project.tsx": $project,
    "./routes/projects.tsx": $projects,
    "./routes/pubs.tsx": $pubs,
    "./routes/research.tsx": $research,
    "./routes/research_topics.tsx": $research_topics,
    "./routes/search.tsx": $search,
    "./routes/service_topics.tsx": $service_topics,
    "./routes/services.tsx": $services,
    "./routes/sitemap.txt.ts": $sitemap_txt,
    "./routes/topics.tsx": $topics,
    "./routes/usr.tsx": $usr,
    "./routes/videos.tsx": $videos,
  },
  islands: {
    "./islands/HScrollWithDynamicImage.tsx": $HScrollWithDynamicImage,
    "./islands/button_open_dialog.tsx": $button_open_dialog,
    "./islands/doi_search.tsx": $doi_search,
    "./islands/lang_switcher.tsx": $lang_switcher,
    "./islands/text.tsx": $text,
    "./islands/theme_switcher.tsx": $theme_switcher,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
