// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_kv_list_kv_list_edit from "./routes/(kv)/list/kv_list_edit.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about from "./routes/about.tsx";
import * as $accreditation from "./routes/accreditation.tsx";
import * as $akvaplanist from "./routes/akvaplanist.tsx";
import * as $api_document_slug_ from "./routes/api/_document/[slug].ts";
import * as $api_kv_get_path_ from "./routes/api/kv/get/[...path].ts";
import * as $api_kv_list_key_ from "./routes/api/kv/list/[...key].ts";
import * as $api_mynewsdesk_index from "./routes/api/mynewsdesk/index.ts";
import * as $api_mynewsdesk_type_path_ from "./routes/api/mynewsdesk/type/[...path].ts";
import * as $api_mynewsdesk_year_path_ from "./routes/api/mynewsdesk/year/[...path].ts";
import * as $api_projects from "./routes/api/projects.ts";
import * as $api_search from "./routes/api/search.ts";
import * as $api_slug_type_ from "./routes/api/slug/[type].ts";
import * as $article_slug_ from "./routes/article/[slug].tsx";
import * as $bento from "./routes/bento.tsx";
import * as $bento_slug_ from "./routes/bento/[slug].tsx";
import * as $careers from "./routes/careers.tsx";
import * as $dcat from "./routes/dcat.tsx";
import * as $document_MarkdownArticlePage from "./routes/document/MarkdownArticlePage.tsx";
import * as $document_slug_ from "./routes/document/[slug].tsx";
import * as $documents from "./routes/documents.tsx";
import * as $doi from "./routes/doi.tsx";
import * as $fakturering from "./routes/fakturering.tsx";
import * as $home from "./routes/home.tsx";
import * as $image from "./routes/image.tsx";
import * as $images from "./routes/images.tsx";
import * as $index from "./routes/index.tsx";
import * as $legacy from "./routes/legacy.tsx";
import * as $legacy_pages_redirect from "./routes/legacy_pages_redirect.tsx";
import * as $ms_louise from "./routes/ms-louise.tsx";
import * as $mynewsdesk_slug_ from "./routes/mynewsdesk/[slug].tsx";
import * as $nav from "./routes/nav.tsx";
import * as $news from "./routes/news.tsx";
import * as $null from "./routes/null.tsx";
import * as $offices from "./routes/offices.tsx";
import * as $policies from "./routes/policies.tsx";
import * as $pref from "./routes/pref.tsx";
import * as $priors from "./routes/priors.tsx";
import * as $project from "./routes/project.tsx";
import * as $projects from "./routes/projects.tsx";
import * as $pubs from "./routes/pubs.tsx";
import * as $research from "./routes/research.tsx";
import * as $research_topics from "./routes/research_topics.tsx";
import * as $search from "./routes/search.tsx";
import * as $service_edit from "./routes/service_edit.tsx";
import * as $service_topics from "./routes/service_topics.tsx";
import * as $services from "./routes/services.tsx";
import * as $services_vt from "./routes/services_vt.tsx";
import * as $sitemap_txt from "./routes/sitemap.txt.ts";
import * as $topics from "./routes/topics.tsx";
import * as $usr from "./routes/usr.tsx";
import * as $video from "./routes/video.tsx";
import * as $videos from "./routes/videos.tsx";
import * as $HScrollWithDynamicImage from "./islands/HScrollWithDynamicImage.tsx";
import * as $KvTextInput from "./islands/KvTextInput.tsx";
import * as $button_open_dialog from "./islands/button_open_dialog.tsx";
import * as $collection_search from "./islands/collection_search.tsx";
import * as $doi_search from "./islands/doi_search.tsx";
import * as $grouped_search from "./islands/grouped_search.tsx";
import * as $grouped_search_collection_results from "./islands/grouped_search_collection_results.tsx";
import * as $lang_switcher from "./islands/lang_switcher.tsx";
import * as $our_x from "./islands/our_x.tsx";
import * as $text from "./islands/text.tsx";
import * as $theme_switcher from "./islands/theme_switcher.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(kv)/list/kv_list_edit.tsx": $_kv_list_kv_list_edit,
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about.tsx": $about,
    "./routes/accreditation.tsx": $accreditation,
    "./routes/akvaplanist.tsx": $akvaplanist,
    "./routes/api/_document/[slug].ts": $api_document_slug_,
    "./routes/api/kv/get/[...path].ts": $api_kv_get_path_,
    "./routes/api/kv/list/[...key].ts": $api_kv_list_key_,
    "./routes/api/mynewsdesk/index.ts": $api_mynewsdesk_index,
    "./routes/api/mynewsdesk/type/[...path].ts": $api_mynewsdesk_type_path_,
    "./routes/api/mynewsdesk/year/[...path].ts": $api_mynewsdesk_year_path_,
    "./routes/api/projects.ts": $api_projects,
    "./routes/api/search.ts": $api_search,
    "./routes/api/slug/[type].ts": $api_slug_type_,
    "./routes/article/[slug].tsx": $article_slug_,
    "./routes/bento.tsx": $bento,
    "./routes/bento/[slug].tsx": $bento_slug_,
    "./routes/careers.tsx": $careers,
    "./routes/dcat.tsx": $dcat,
    "./routes/document/MarkdownArticlePage.tsx": $document_MarkdownArticlePage,
    "./routes/document/[slug].tsx": $document_slug_,
    "./routes/documents.tsx": $documents,
    "./routes/doi.tsx": $doi,
    "./routes/fakturering.tsx": $fakturering,
    "./routes/home.tsx": $home,
    "./routes/image.tsx": $image,
    "./routes/images.tsx": $images,
    "./routes/index.tsx": $index,
    "./routes/legacy.tsx": $legacy,
    "./routes/legacy_pages_redirect.tsx": $legacy_pages_redirect,
    "./routes/ms-louise.tsx": $ms_louise,
    "./routes/mynewsdesk/[slug].tsx": $mynewsdesk_slug_,
    "./routes/nav.tsx": $nav,
    "./routes/news.tsx": $news,
    "./routes/null.tsx": $null,
    "./routes/offices.tsx": $offices,
    "./routes/policies.tsx": $policies,
    "./routes/pref.tsx": $pref,
    "./routes/priors.tsx": $priors,
    "./routes/project.tsx": $project,
    "./routes/projects.tsx": $projects,
    "./routes/pubs.tsx": $pubs,
    "./routes/research.tsx": $research,
    "./routes/research_topics.tsx": $research_topics,
    "./routes/search.tsx": $search,
    "./routes/service_edit.tsx": $service_edit,
    "./routes/service_topics.tsx": $service_topics,
    "./routes/services.tsx": $services,
    "./routes/services_vt.tsx": $services_vt,
    "./routes/sitemap.txt.ts": $sitemap_txt,
    "./routes/topics.tsx": $topics,
    "./routes/usr.tsx": $usr,
    "./routes/video.tsx": $video,
    "./routes/videos.tsx": $videos,
  },
  islands: {
    "./islands/HScrollWithDynamicImage.tsx": $HScrollWithDynamicImage,
    "./islands/KvTextInput.tsx": $KvTextInput,
    "./islands/button_open_dialog.tsx": $button_open_dialog,
    "./islands/collection_search.tsx": $collection_search,
    "./islands/doi_search.tsx": $doi_search,
    "./islands/grouped_search.tsx": $grouped_search,
    "./islands/grouped_search_collection_results.tsx":
      $grouped_search_collection_results,
    "./islands/lang_switcher.tsx": $lang_switcher,
    "./islands/our_x.tsx": $our_x,
    "./islands/text.tsx": $text,
    "./islands/theme_switcher.tsx": $theme_switcher,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
