// {
// "id": "https://api.nva.unit.no/cristin/project/2572443",
// "type": "Project",
// "identifiers": [],
// "title": "SeaBee - Norwegian Infrastructure for drone-based research, mapping and monitoring in the coastal zone",
// "language": "http://lexvo.org/id/iso639-3/eng",
// "alternativeTitles": [],
// "startDate": "2020-04-01T00:00:00Z",
// "endDate": "2029-03-31T00:00:00Z",
// "funding": [],
// "coordinatingInstitution": {},
// "contributors": [],
// "status": "ACTIVE",
// "academicSummary": {},
// "popularScientificSummary": {},
// "published": true,
// "publishable": true,
// "created": {},
// "lastModified": {},
// "contactInfo": {},
// "fundingAmount": {},
// "method": {},
// "equipment": {},
// "projectCategories": [],
// "keywords": [],
// "externalSources": [],
// "relatedProjects": [],
// "institutionsResponsibleForResearch": [],
// "approvals": [],
// "creator": {},
// "webPage": "https://www.seabee.no/",
// "@context": "https://bibsysdev.github.io/src/project-context.json"
// }
